import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import pg from "pg";
import { loadEnv } from "./env.js";

/**
 * Apply the committed migrations, in order.
 *
 * Deliberately plain: the SQL in `packages/schema/migrations` is generated by
 * drizzle-kit, reviewed, and committed. Nothing is generated at deploy time, and
 * the same files run here and in the integration tests.
 */

const MIGRATIONS_DIR = path.resolve(
  import.meta.dirname,
  "../../../packages/schema/migrations",
);

const env = loadEnv();
const pool = new pg.Pool({ connectionString: env.DATABASE_URL });

await pool.query(`
  CREATE TABLE IF NOT EXISTS _migrations (
    name TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )
`);

const applied = new Set(
  (await pool.query<{ name: string }>("SELECT name FROM _migrations")).rows.map((r) => r.name),
);

const files = (await readdir(MIGRATIONS_DIR)).filter((f) => f.endsWith(".sql")).sort();

for (const file of files) {
  if (applied.has(file)) continue;
  const sql = await readFile(path.join(MIGRATIONS_DIR, file), "utf8");
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(sql);
    await client.query("INSERT INTO _migrations (name) VALUES ($1)", [file]);
    await client.query("COMMIT");
    process.stdout.write(`applied ${file}\n`);
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

await pool.end();
process.stdout.write("migrations up to date\n");
